openapi: 3.0.0
info:
  title: All new Branded Tshirt
  description: Developed By - Deepz
  version: 0.1.1

servers:
  - url: "{protocol}://localhost:5000/api/"
    description: localhost version of the app
    variables:
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
    cookieAuth:
      type: apiKey
      in: cookie
      name: token

paths:
  /auth/signup:
    post:
      tags:
        - Authentication
      summary: create a new user
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                  name:
                    type: string
                  email:
                    type: string
                  password:
                    type: string
                  photo:
                    type: string
                    format: binary   
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  token: 
                    type: string
                  user:
                    type: object
                    properties:
                      name:
                        type: string 
                      email:
                        type: string 
                      role:
                        type: string 
                      _id:
                        type: string 
                      createdAt:
                        type: string 
        '400':
          description: Bad request
        '500':
          description: 'Internal server error'
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                  email:
                    type: string
                  password:
                    type: string   
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  token: 
                    type: string
                  user:
                    type: object
                    properties:
                      name:
                        type: string 
                      email:
                        type: string 
                      role:
                        type: string 
                      _id:
                        type: string 
                      createdAt:
                        type: string 
        '400':
          description: Bad request
        '500':
          description: 'Internal server error'
  /auth/logout:
    get:
      tags:
        - Authentication
      summary: Logout  
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  message: 
                    type: string
        '400':
          description: Bad request
        '500':
          description: 'Internal server error'
  /auth/forgotpassword:
    post:
      tags:
        - Authentication
      summary: Forgot Password
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                  email:
                    type: string  
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  message: 
                    type: string 
        '400':
          description: Bad request
        '500':
          description: 'Internal server error'
  /auth/password/reset/{token}:
    post:
      tags:
        - Authentication
      summary: Forgot Password
      parameters:
        - name: token
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                  password:
                    type: string  
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  token: 
                    type: string
                  user:
                    type: object
                    properties:
                      name:
                        type: string 
                      email:
                        type: string 
                      role:
                        type: string 
                      _id:
                        type: string 
                      createdAt:
                        type: string 
        '400':
          description: Bad request
        '500':
          description: 'Internal server error'

  /user/userinfo:
    get:
      tags:
        - User
      summary: Get a user
      security:
        - BearerAuth: []  
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  token: 
                    type: string
                  user:
                    type: object
                    properties:
                      photo:
                        type: object
                        properties:
                          id:
                            type: string
                          secure_url:
                            type: string  
                      name:
                        type: string 
                      email:
                        type: string 
                      role:
                        type: string 
                      _id:
                        type: string 
                      createdAt:
                        type: string 
        '400':
          description: Bad request
        '500':
          description: 'Internal server error'        
  /user/changepassword:
    post:
      tags:
        - User
      summary: Change user Password
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                  oldPassword:
                    type: string    
                  newPassword:
                    type: string    
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  token: 
                    type: string
                  user:
                    type: object
                    properties:
                      photo:
                        type: object
                        properties:
                          id:
                            type: string
                          secure_url:
                            type: string  
                      name:
                        type: string 
                      email:
                        type: string 
                      role:
                        type: string 
                      _id:
                        type: string 
                      createdAt:
                        type: string 
        '400':
          description: Bad request
        '500':
          description: 'Internal server error'        
  /user/updateUser:
    post:
      tags:
        - User
      summary: Update user
      security:
        - BearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                  name:
                    type: string
                    required: true    
                  email:
                    type: string
                    required: true
                  photo:
                    type: string
                    format: binary      
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  token: 
                    type: string
                  user:
                    type: object
                    properties:
                      photo:
                        type: object
                        properties:
                          id:
                            type: string
                          secure_url:
                            type: string  
                      name:
                        type: string 
                      email:
                        type: string 
                      role:
                        type: string 
                      _id:
                        type: string 
                      createdAt:
                        type: string 
        '400':
          description: Bad request
        '500':
          description: 'Internal server error'        
  
  /user/admin/allusers:
    get:
      tags:
        - Admin
      summary: get all users
      security:
        - BearerAuth: []      
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  token: 
                    type: string
                  user:
                    type: array
                    items:
                      type: object
                      properties:
                        photo:
                          type: object
                          properties:
                            id:
                              type: string
                            secure_url:
                              type: string  
                        name:
                          type: string 
                        email:
                          type: string 
                        role:
                          type: string 
                        _id:
                          type: string 
                        createdAt:
                          type: string 
        '400':
          description: Bad request
        '500':
          description: 'Internal server error'        

  /user/manager/allusers:
    get:
      tags:
        - Manager
      summary: get all users
      security:
        - BearerAuth: []      
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  token: 
                    type: string
                  user:
                    type: array
                    items:
                      type: object
                      properties:
                        photo:
                          type: object
                          properties:
                            id:
                              type: string
                            secure_url:
                              type: string  
                        name:
                          type: string 
                        email:
                          type: string 
                        role:
                          type: string 
                        _id:
                          type: string 
                        createdAt:
                          type: string 
        '400':
          description: Bad request
        '500':
          description: 'Internal server error' 