openapi: 3.0.0
info:
  title: All new Branded Tshirt
  description: Developed By - Deepz
  version: 0.1.1

servers:
  - url: "{protocol}://localhost:5000/api/"
    description: localhost version of the app
    variables:
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
    cookieAuth:
      type: apiKey
      in: cookie
      name: token

paths:
  /auth/signup:
    post:
      tags:
        - Authentication
      summary: create a new user
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                  name:
                    type: string
                  email:
                    type: string
                  password:
                    type: string
                  photo:
                    type: string
                    format: binary   
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  token: 
                    type: string
                  user:
                    type: object
                    properties:
                      name:
                        type: string 
                      email:
                        type: string 
                      role:
                        type: string 
                      _id:
                        type: string 
                      createdAt:
                        type: string 
        '400':
          description: Bad request
        '500':
          description: 'Internal server error'
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                  email:
                    type: string
                  password:
                    type: string   
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: 
                    type: boolean
                  token: 
                    type: string
                  user:
                    type: object
                    properties:
                      name:
                        type: string 
                      email:
                        type: string 
                      role:
                        type: string 
                      _id:
                        type: string 
                      createdAt:
                        type: string 
        '400':
          description: Bad request
        '500':
          description: 'Internal server error'
